# ==========================================================
# Docker Compose Configuration
# ==========================================================
#
# Project:
# AWS DevOps CloudFormation Lab
#
# Purpose:
# - Build the Docker image
# - Start a reusable development container
# - Mount the project folder
# - Mount AWS credentials
# - Set AWS default region
#
# ==========================================================

services:

  aws-lab:

    # ------------------------------------------------------
    # Build Docker Image
    # ------------------------------------------------------
    build:
      context: ..
      dockerfile: docker/Dockerfile

    # ------------------------------------------------------
    # Container Name
    # ------------------------------------------------------
    container_name: aws-cloudformation-lab

    # ------------------------------------------------------
    # Interactive Terminal
    # ------------------------------------------------------
    stdin_open: true
    tty: true

    # ------------------------------------------------------
    # Automatically restart unless stopped manually
    # ------------------------------------------------------
    restart: unless-stopped

    # ------------------------------------------------------
    # Working Directory
    # ------------------------------------------------------
    working_dir: /workspace

    # ------------------------------------------------------
    # Mount Local Project
    # ------------------------------------------------------
    # The entire project is available inside the container.
    volumes:

      # Project folder
      - ../:/workspace

      # AWS credentials
      # Linux/macOS
      - ~/.aws:/root/.aws:ro

      # Windows users can replace the above line with:
      # - C:/Users/<YourUserName>/.aws:/root/.aws:ro

    # ------------------------------------------------------
    # Environment Variables
    # ------------------------------------------------------
    environment:
      AWS_DEFAULT_REGION: us-east-1

    # ------------------------------------------------------
    # Default Command
    # ------------------------------------------------------
    command: /bin/bash