#!/bin/bash

# ============================================================================
# AWS CLOUDFORMATION DEVOPS LAB
# COMPLETE EC2 READ-ONLY VERIFICATION SCRIPT
# ============================================================================
#
# File:
#
#   verify-cloudformation-lab.sh
#
# Purpose:
#
#   Perform a complete read-only verification of the AWS CloudFormation
#   DevOps Lab from inside an EC2 instance.
#
# ============================================================================
#
# IMPORTANT:
#
# This script is intended for VERIFICATION ONLY.
#
# It does NOT intentionally:
#
#   - Create AWS resources
#   - Update AWS resources
#   - Delete AWS resources
#   - Start EC2 instances
#   - Stop EC2 instances
#   - Restart ECS services
#   - Change ECS desired count
#   - Push Docker images
#   - Push ECR images
#   - Modify IAM permissions
#   - Modify Security Groups
#   - Modify Route Tables
#   - Modify VPC Endpoints
#   - Modify RDS
#   - Modify S3
#
# ============================================================================
#
# VERIFICATION AREAS
#
#   1.  Linux OS
#   2.  Host information
#   3.  Current user
#   4.  Kernel / architecture
#   5.  Disk
#   6.  Memory
#   7.  CPU
#   8.  AWS CLI
#   9.  AWS identity
#   10. EC2 metadata
#   11. CloudFormation main stack
#   12. CloudFormation outputs
#   13. CloudFormation resources
#   14. Nested stacks
#   15. VPC
#   16. VPC DNS
#   17. Internet Gateway
#   18. Subnets
#   19. Route tables
#   20. NAT Gateways
#   21. Network ACLs
#   22. Security Groups
#   23. VPC Endpoints
#   24. EC2 instance
#   25. EC2 health
#   26. UserData / Cloud-init
#   27. Internet connectivity
#   28. DNS
#   29. Apache
#   30. Nginx
#   31. PHP
#   32. Docker
#   33. Docker Compose
#   34. Docker containers
#   35. Docker images
#   36. Listening ports
#   37. Git
#   38. S3 buckets
#   39. S3 bucket properties
#   40. S3 objects
#   41. S3 website configuration
#   42. CloudFront distributions
#   43. CloudFront -> S3 configuration
#   44. CloudFront website test
#   45. RDS MySQL
#   46. RDS network connectivity
#   47. Secrets Manager
#   48. ECR
#   49. ECR images
#   50. ECS CloudFormation stack
#   51. ECS cluster
#   52. ECS service
#   53. ECS tasks
#   54. ECS task health
#   55. Application Load Balancer
#   56. ALB listeners
#   57. Target Groups
#   58. Target Health
#   59. ALB HTTP test
#   60. CloudWatch Logs
#   61. Final EC2 -> RDS test
#   62. Final summary
#
# ============================================================================


# ============================================================================
# 1. CONFIGURATION
# ============================================================================

AWS_REGION="us-east-1"

# --------------------------------------------------------------------------
# Optional AWS profile.
#
# Leave empty when EC2 IAM Role credentials are being used.
# --------------------------------------------------------------------------

AWS_PROFILE=""

# --------------------------------------------------------------------------
# CloudFormation stacks
# --------------------------------------------------------------------------

MAIN_STACK="Main-CloudFormation"

ECS_STACK="CharlieCafe-ECS-Stack"

# --------------------------------------------------------------------------
# Expected VPC
# --------------------------------------------------------------------------

EXPECTED_VPC_CIDR="10.0.0.0/16"

# --------------------------------------------------------------------------
# ECS
# --------------------------------------------------------------------------

ECR_REPOSITORY="charlie-cafe"

ECS_CLUSTER="CharlieCafe-Cluster"

ECS_SERVICE="CharlieCafe-Service"

CONTAINER_PORT="80"

# --------------------------------------------------------------------------
# CloudWatch
# --------------------------------------------------------------------------

LOG_GROUP="/ecs/charlie-cafe"

# --------------------------------------------------------------------------
# Expected application ports
# --------------------------------------------------------------------------

HTTP_PORT="80"

HTTPS_PORT="443"

DOCKER_APP_PORT="8080"

# --------------------------------------------------------------------------
# Optional expected S3 website bucket name.
#
# Leave empty if the bucket name is generated by CloudFormation.
# The script will discover buckets from CloudFormation outputs.
# --------------------------------------------------------------------------

EXPECTED_WEBSITE_BUCKET=""

# ============================================================================
# 2. VERIFICATION COUNTERS
# ============================================================================

PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0


# ============================================================================
# 3. AWS CLI CONFIGURATION
# ============================================================================

export AWS_PAGER=""

export AWS_DEFAULT_REGION="$AWS_REGION"

if [ -n "$AWS_PROFILE" ]; then

    export AWS_PROFILE

fi


# ============================================================================
# 4. OUTPUT FUNCTIONS
# ============================================================================

print_header() {

    echo
    echo "======================================================================"
    echo "$1"
    echo "======================================================================"

}


pass() {

    echo "[PASS] $1"

    PASS_COUNT=$((PASS_COUNT + 1))

}


fail() {

    echo "[FAIL] $1"

    FAIL_COUNT=$((FAIL_COUNT + 1))

}


warn() {

    echo "[WARN] $1"

    WARN_COUNT=$((WARN_COUNT + 1))

}


info() {

    echo "[INFO] $1"

}


# ============================================================================
# 5. BASIC SYSTEM INFORMATION
# ============================================================================

print_header "1. EC2 OPERATING SYSTEM"

if [ -f "/etc/os-release" ]; then

    pass "OS information file exists."

    cat /etc/os-release

else

    fail "Unable to read /etc/os-release."

fi


print_header "2. HOST INFORMATION"

if command -v hostnamectl >/dev/null 2>&1; then

    hostnamectl

    pass "Host information retrieved."

else

    warn "hostnamectl is not available."

    hostname

fi


print_header "3. CURRENT USER"

CURRENT_USER=$(whoami)

echo "Current User: $CURRENT_USER"

if [ -n "$CURRENT_USER" ]; then

    pass "Current user detected: $CURRENT_USER"

else

    fail "Unable to determine current user."

fi


print_header "4. KERNEL / ARCHITECTURE"

uname -a

ARCHITECTURE=$(uname -m)

echo
echo "Architecture: $ARCHITECTURE"

pass "Kernel and architecture information retrieved."


print_header "5. DISK USAGE"

df -h

pass "Disk usage information retrieved."


print_header "6. MEMORY"

free -h

pass "Memory information retrieved."


print_header "7. CPU"

echo "CPU Count:"

nproc

pass "CPU information retrieved."


# ============================================================================
# 6. AWS CLI
# ============================================================================

print_header "8. AWS CLI VERIFICATION"

if command -v aws >/dev/null 2>&1; then

    pass "AWS CLI is installed."

    aws --version

else

    fail "AWS CLI is not installed."

fi


# ============================================================================
# 7. AWS IDENTITY
# ============================================================================

print_header "9. AWS IDENTITY / IAM"

if aws sts get-caller-identity \
    --region "$AWS_REGION" \
    >/dev/null 2>&1; then

    pass "EC2 can authenticate to AWS."

    AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
        --region "$AWS_REGION" \
        --query "Account" \
        --output text)

    AWS_CALLER_ARN=$(aws sts get-caller-identity \
        --region "$AWS_REGION" \
        --query "Arn" \
        --output text)

    echo
    echo "AWS Account ID:"
    echo "$AWS_ACCOUNT_ID"

    echo
    echo "Caller ARN:"
    echo "$AWS_CALLER_ARN"

else

    fail "EC2 cannot authenticate to AWS."

    AWS_ACCOUNT_ID=""

    AWS_CALLER_ARN=""

fi


# ============================================================================
# 8. EC2 INSTANCE METADATA
# ============================================================================

print_header "10. EC2 INSTANCE METADATA"

TOKEN=$(curl -sS \
    --connect-timeout 3 \
    --max-time 5 \
    -X PUT \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" \
    http://169.254.169.254/latest/api/token \
    2>/dev/null)

if [ -n "$TOKEN" ]; then

    pass "EC2 Instance Metadata Service is accessible."

    INSTANCE_ID_LOCAL=$(curl -sS \
        --connect-timeout 3 \
        --max-time 5 \
        -H "X-aws-ec2-metadata-token: $TOKEN" \
        http://169.254.169.254/latest/meta-data/instance-id \
        2>/dev/null)

    INSTANCE_TYPE_LOCAL=$(curl -sS \
        --connect-timeout 3 \
        --max-time 5 \
        -H "X-aws-ec2-metadata-token: $TOKEN" \
        http://169.254.169.254/latest/meta-data/instance-type \
        2>/dev/null)

    PRIVATE_IP_LOCAL=$(curl -sS \
        --connect-timeout 3 \
        --max-time 5 \
        -H "X-aws-ec2-metadata-token: $TOKEN" \
        http://169.254.169.254/latest/meta-data/local-ipv4 \
        2>/dev/null)

    AVAILABILITY_ZONE_LOCAL=$(curl -sS \
        --connect-timeout 3 \
        --max-time 5 \
        -H "X-aws-ec2-metadata-token: $TOKEN" \
        http://169.254.169.254/latest/meta-data/placement/availability-zone \
        2>/dev/null)

    IAM_ROLE_LOCAL=$(curl -sS \
        --connect-timeout 3 \
        --max-time 5 \
        -H "X-aws-ec2-metadata-token: $TOKEN" \
        http://169.254.169.254/latest/meta-data/iam/security-credentials/ \
        2>/dev/null)

    echo
    echo "Instance ID       : $INSTANCE_ID_LOCAL"
    echo "Instance Type     : $INSTANCE_TYPE_LOCAL"
    echo "Private IP        : $PRIVATE_IP_LOCAL"
    echo "Availability Zone : $AVAILABILITY_ZONE_LOCAL"
    echo "IAM Role          : ${IAM_ROLE_LOCAL:-NONE}"

    if [ -n "$IAM_ROLE_LOCAL" ]; then

        pass "EC2 IAM role is visible through instance metadata."

    else

        warn "No EC2 IAM role was detected through metadata."

    fi

else

    warn "EC2 Instance Metadata Service could not be accessed."

    INSTANCE_ID_LOCAL=""

fi


# ============================================================================
# 9. CLOUDFORMATION MAIN STACK
# ============================================================================

print_header "11. MAIN CLOUDFORMATION STACK"

MAIN_STACK_STATUS=$(aws cloudformation describe-stacks \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "Stacks[0].StackStatus" \
    --output text \
    2>/dev/null)

if [ "$MAIN_STACK_STATUS" = "CREATE_COMPLETE" ] || \
   [ "$MAIN_STACK_STATUS" = "UPDATE_COMPLETE" ]; then

    pass "Main CloudFormation stack status: $MAIN_STACK_STATUS"

else

    if [ -z "$MAIN_STACK_STATUS" ] || \
       [ "$MAIN_STACK_STATUS" = "None" ]; then

        fail "Main CloudFormation stack was not found."

    else

        fail "Main CloudFormation stack status: $MAIN_STACK_STATUS"

    fi

fi


# ============================================================================
# 10. CLOUDFORMATION OUTPUTS
# ============================================================================

print_header "12. MAIN CLOUDFORMATION OUTPUTS"

aws cloudformation describe-stacks \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[*].[OutputKey,OutputValue]" \
    --output table \
    2>/dev/null

if [ $? -eq 0 ]; then

    pass "CloudFormation outputs retrieved."

else

    fail "Unable to retrieve CloudFormation outputs."

fi


# ============================================================================
# 11. CLOUDFORMATION RESOURCES
# ============================================================================

print_header "13. MAIN CLOUDFORMATION RESOURCES"

aws cloudformation list-stack-resources \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "StackResourceSummaries[*].[LogicalResourceId,ResourceType,ResourceStatus]" \
    --output table \
    2>/dev/null

if [ $? -eq 0 ]; then

    pass "CloudFormation resources retrieved."

else

    fail "Unable to retrieve CloudFormation resources."

fi


# ============================================================================
# 12. NESTED STACKS
# ============================================================================

print_header "14. NESTED CLOUDFORMATION STACKS"

NESTED_STACKS=$(aws cloudformation list-stack-resources \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "StackResourceSummaries[?ResourceType=='AWS::CloudFormation::Stack'].[LogicalResourceId,PhysicalResourceId,ResourceStatus]" \
    --output table \
    2>/dev/null)

if [ -n "$NESTED_STACKS" ]; then

    echo "$NESTED_STACKS"

    pass "Nested CloudFormation stacks detected."

else

    warn "No nested CloudFormation stacks detected."

fi


# ============================================================================
# 13. VPC
# ============================================================================

print_header "15. VPC VERIFICATION"

VPC_ID=$(aws cloudformation describe-stacks \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?contains(OutputKey,'Vpc') || contains(OutputKey,'VPC')].OutputValue | [0]" \
    --output text \
    2>/dev/null)

if [ -z "$VPC_ID" ] || [ "$VPC_ID" = "None" ]; then

    info "VPC ID not found from CloudFormation outputs."

    info "Searching by expected CIDR: $EXPECTED_VPC_CIDR"

    VPC_ID=$(aws ec2 describe-vpcs \
        --region "$AWS_REGION" \
        --filters "Name=cidr-block,Values=$EXPECTED_VPC_CIDR" \
        --query "Vpcs[0].VpcId" \
        --output text \
        2>/dev/null)

fi


if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    pass "VPC found: $VPC_ID"

    VPC_CIDR=$(aws ec2 describe-vpcs \
        --vpc-ids "$VPC_ID" \
        --region "$AWS_REGION" \
        --query "Vpcs[0].CidrBlock" \
        --output text)

    VPC_STATE=$(aws ec2 describe-vpcs \
        --vpc-ids "$VPC_ID" \
        --region "$AWS_REGION" \
        --query "Vpcs[0].State" \
        --output text)

    echo
    echo "VPC ID    : $VPC_ID"
    echo "VPC CIDR  : $VPC_CIDR"
    echo "VPC State : $VPC_STATE"

    if [ "$VPC_CIDR" = "$EXPECTED_VPC_CIDR" ]; then

        pass "VPC CIDR matches expected CIDR."

    else

        warn "VPC CIDR is $VPC_CIDR instead of $EXPECTED_VPC_CIDR."

    fi

else

    fail "VPC could not be identified."

fi


# ============================================================================
# 14. VPC DNS
# ============================================================================

print_header "16. VPC DNS VERIFICATION"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    DNS_SUPPORT=$(aws ec2 describe-vpc-attribute \
        --vpc-id "$VPC_ID" \
        --attribute enableDnsSupport \
        --region "$AWS_REGION" \
        --query "EnableDnsSupport.Value" \
        --output text \
        2>/dev/null)

    DNS_HOSTNAMES=$(aws ec2 describe-vpc-attribute \
        --vpc-id "$VPC_ID" \
        --attribute enableDnsHostnames \
        --region "$AWS_REGION" \
        --query "EnableDnsHostnames.Value" \
        --output text \
        2>/dev/null)

    echo "DNS Support   : $DNS_SUPPORT"
    echo "DNS Hostnames : $DNS_HOSTNAMES"

    if [ "$DNS_SUPPORT" = "True" ]; then

        pass "VPC DNS support is enabled."

    else

        fail "VPC DNS support is disabled."

    fi

    if [ "$DNS_HOSTNAMES" = "True" ]; then

        pass "VPC DNS hostnames are enabled."

    else

        fail "VPC DNS hostnames are disabled."

    fi

fi


# ============================================================================
# 15. INTERNET GATEWAY
# ============================================================================

print_header "17. INTERNET GATEWAY"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    IGW_ID=$(aws ec2 describe-internet-gateways \
        --region "$AWS_REGION" \
        --filters "Name=attachment.vpc-id,Values=$VPC_ID" \
        --query "InternetGateways[0].InternetGatewayId" \
        --output text \
        2>/dev/null)

    if [ -n "$IGW_ID" ] && [ "$IGW_ID" != "None" ]; then

        pass "Internet Gateway is attached: $IGW_ID"

        aws ec2 describe-internet-gateways \
            --internet-gateway-ids "$IGW_ID" \
            --region "$AWS_REGION" \
            --query "InternetGateways[0].[InternetGatewayId,Attachments[0].State]" \
            --output table

    else

        fail "No Internet Gateway is attached."

    fi

fi


# ============================================================================
# 16. SUBNETS
# ============================================================================

print_header "18. VPC SUBNETS"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    aws ec2 describe-subnets \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "Subnets[*].[SubnetId,AvailabilityZone,CidrBlock,MapPublicIpOnLaunch,Tags[?Key=='Name'].Value|[0]]" \
        --output table

    SUBNET_COUNT=$(aws ec2 describe-subnets \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "length(Subnets)" \
        --output text \
        2>/dev/null)

    echo
    echo "Subnet Count: $SUBNET_COUNT"

    if [ "$SUBNET_COUNT" -ge 4 ]; then

        pass "At least four subnets found."

    else

        warn "Only $SUBNET_COUNT subnet(s) found."

    fi

fi


# ============================================================================
# 17. ROUTE TABLES
# ============================================================================

print_header "19. ROUTE TABLES"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    ROUTE_TABLE_COUNT=$(aws ec2 describe-route-tables \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "length(RouteTables)" \
        --output text \
        2>/dev/null)

    echo "Route Table Count: $ROUTE_TABLE_COUNT"

    aws ec2 describe-route-tables \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "RouteTables[*].[RouteTableId,Routes[*].[DestinationCidrBlock,GatewayId,NatGatewayId],Associations[*].SubnetId,Tags[?Key=='Name'].Value|[0]]" \
        --output table

    if [ "$ROUTE_TABLE_COUNT" -gt 0 ]; then

        pass "VPC route tables retrieved."

    else

        fail "No VPC route tables found."

    fi

fi


# ============================================================================
# 18. NAT GATEWAYS
# ============================================================================

print_header "20. NAT GATEWAYS"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    NAT_COUNT=$(aws ec2 describe-nat-gateways \
        --region "$AWS_REGION" \
        --filter "Name=vpc-id,Values=$VPC_ID" \
        --query "length(NatGateways)" \
        --output text \
        2>/dev/null)

    echo "NAT Gateway Count: ${NAT_COUNT:-0}"

    aws ec2 describe-nat-gateways \
        --region "$AWS_REGION" \
        --filter "Name=vpc-id,Values=$VPC_ID" \
        --query "NatGateways[*].[NatGatewayId,State,SubnetId,ConnectivityType]" \
        --output table

    if [ "${NAT_COUNT:-0}" -gt 0 ]; then

        pass "NAT Gateway(s) found."

    else

        warn "No NAT Gateway found. This may be intentional for this lab."

    fi

fi


# ============================================================================
# 19. NETWORK ACLS
# ============================================================================

print_header "21. NETWORK ACLS"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    NACL_COUNT=$(aws ec2 describe-network-acls \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "length(NetworkAcls)" \
        --output text \
        2>/dev/null)

    echo "Network ACL Count: ${NACL_COUNT:-0}"

    aws ec2 describe-network-acls \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "NetworkAcls[*].[NetworkAclId,IsDefault,Tags[?Key=='Name'].Value|[0]]" \
        --output table

    if [ "${NACL_COUNT:-0}" -gt 0 ]; then

        pass "Network ACLs retrieved."

    else

        fail "No Network ACLs found."

    fi

fi


# ============================================================================
# 20. SECURITY GROUPS
# ============================================================================

print_header "22. SECURITY GROUPS"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    SG_COUNT=$(aws ec2 describe-security-groups \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "length(SecurityGroups)" \
        --output text \
        2>/dev/null)

    echo "Security Group Count: ${SG_COUNT:-0}"

    aws ec2 describe-security-groups \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "SecurityGroups[*].[GroupId,GroupName,Description]" \
        --output table

    if [ "${SG_COUNT:-0}" -gt 0 ]; then

        pass "Security groups retrieved."

    else

        fail "No security groups found."

    fi

fi


# ============================================================================
# 21. VPC ENDPOINTS
# ============================================================================

print_header "23. VPC ENDPOINTS"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

    ENDPOINT_COUNT=$(aws ec2 describe-vpc-endpoints \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "length(VpcEndpoints)" \
        --output text \
        2>/dev/null)

    echo "VPC Endpoint Count: ${ENDPOINT_COUNT:-0}"

    aws ec2 describe-vpc-endpoints \
        --region "$AWS_REGION" \
        --filters "Name=vpc-id,Values=$VPC_ID" \
        --query "VpcEndpoints[*].[VpcEndpointId,ServiceName,VpcEndpointType,State]" \
        --output table

    if [ "${ENDPOINT_COUNT:-0}" -ge 3 ]; then

        pass "At least three VPC endpoints found."

    elif [ "${ENDPOINT_COUNT:-0}" -gt 0 ]; then

        warn "VPC endpoints exist, but fewer than three were found."

    else

        warn "No VPC endpoints found."

    fi

fi


# ============================================================================
# 22. EC2 INSTANCE
# ============================================================================

print_header "24. EC2 INSTANCE VERIFICATION"

INSTANCE_ID=""

if [ -n "$INSTANCE_ID_LOCAL" ]; then

    INSTANCE_ID="$INSTANCE_ID_LOCAL"

else

    if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then

        INSTANCE_ID=$(aws ec2 describe-instances \
            --region "$AWS_REGION" \
            --filters \
                "Name=vpc-id,Values=$VPC_ID" \
                "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text \
            2>/dev/null)

    fi

fi


if [ -n "$INSTANCE_ID" ] && [ "$INSTANCE_ID" != "None" ]; then

    pass "EC2 instance found: $INSTANCE_ID"

    aws ec2 describe-instances \
        --instance-ids "$INSTANCE_ID" \
        --region "$AWS_REGION" \
        --query "Reservations[0].Instances[0].[InstanceId,InstanceType,State.Name,SubnetId,PrivateIpAddress,PublicIpAddress,VpcId]" \
        --output table

else

    fail "Running EC2 instance could not be identified."

fi


# ============================================================================
# 23. EC2 HEALTH
# ============================================================================

print_header "25. EC2 SYSTEM HEALTH"

if [ -n "$INSTANCE_ID" ] && [ "$INSTANCE_ID" != "None" ]; then

    INSTANCE_STATUS=$(aws ec2 describe-instance-status \
        --instance-ids "$INSTANCE_ID" \
        --include-all-instances \
        --region "$AWS_REGION" \
        --query "InstanceStatuses[0].[SystemStatus.Status,InstanceStatus.Status]" \
        --output text \
        2>/dev/null)

    echo "EC2 Health:"
    echo "$INSTANCE_STATUS"

    if echo "$INSTANCE_STATUS" | grep -q "ok"; then

        pass "EC2 system and instance checks are healthy."

    else

        warn "EC2 health checks are not both OK."

    fi

fi


# ============================================================================
# 24. USERDATA / CLOUD INIT
# ============================================================================

print_header "26. USERDATA / CLOUD-INIT"

if [ -f "/var/log/cloud-init.log" ]; then

    pass "cloud-init.log exists."

else

    warn "cloud-init.log not found."

fi


if [ -f "/var/log/cloud-init-output.log" ]; then

    pass "cloud-init-output.log exists."

else

    warn "cloud-init-output.log not found."

fi


if [ -f "/var/log/bootstrap.log" ]; then

    pass "bootstrap.log exists."

    echo
    echo "--- Last 20 bootstrap.log lines ---"

    sudo tail -n 20 /var/log/bootstrap.log

else

    warn "bootstrap.log not found."

fi


if [ -f "/var/log/bootstrap-status.log" ]; then

    pass "bootstrap-status.log exists."

    echo
    cat /var/log/bootstrap-status.log

else

    warn "bootstrap-status.log not found."

fi


# ============================================================================
# 25. INTERNET CONNECTIVITY
# ============================================================================

print_header "27. EC2 INTERNET CONNECTIVITY"

if curl -Is \
    --connect-timeout 5 \
    https://www.google.com \
    >/dev/null 2>&1; then

    pass "EC2 HTTPS internet connectivity works."

else

    fail "EC2 cannot reach Google over HTTPS."

fi


if curl -Is \
    --connect-timeout 5 \
    https://github.com \
    >/dev/null 2>&1; then

    pass "EC2 can reach GitHub."

else

    fail "EC2 cannot reach GitHub."

fi


# ============================================================================
# 26. DNS
# ============================================================================

print_header "28. DNS VERIFICATION"

if getent hosts github.com >/dev/null 2>&1; then

    pass "DNS resolution for github.com works."

else

    fail "DNS resolution for github.com failed."

fi


if getent hosts amazonaws.com >/dev/null 2>&1; then

    pass "DNS resolution for amazonaws.com works."

else

    fail "DNS resolution for amazonaws.com failed."

fi


# ============================================================================
# 27. APACHE
# ============================================================================

print_header "29. APACHE VERIFICATION"

if command -v httpd >/dev/null 2>&1; then

    pass "Apache/httpd is installed."

    if systemctl is-active --quiet httpd; then

        pass "Apache is running."

    else

        warn "Apache is installed but not running."

    fi

    if curl -Is \
        --connect-timeout 5 \
        http://localhost \
        >/dev/null 2>&1; then

        pass "Apache responds on localhost."

    else

        warn "Apache does not respond on localhost."

    fi

else

    warn "Apache/httpd is not installed."

fi


# ============================================================================
# 28. NGINX
# ============================================================================

print_header "30. NGINX VERIFICATION"

if command -v nginx >/dev/null 2>&1; then

    pass "Nginx is installed."

    nginx -v 2>&1

    if systemctl is-active --quiet nginx; then

        pass "Nginx service is running."

    else

        warn "Nginx is installed but not running."

    fi

    if curl -Is \
        --connect-timeout 5 \
        http://localhost \
        >/dev/null 2>&1; then

        pass "HTTP localhost responds."

    else

        warn "No HTTP response from localhost."

    fi

else

    warn "Nginx is not installed."

fi


# ============================================================================
# 29. PHP
# ============================================================================

print_header "31. PHP VERIFICATION"

if command -v php >/dev/null 2>&1; then

    pass "PHP is installed."

    php --version | head -n 1

else

    warn "PHP is not installed."

fi


# ============================================================================
# 30. DOCKER
# ============================================================================

print_header "32. DOCKER VERIFICATION"

if command -v docker >/dev/null 2>&1; then

    pass "Docker is installed."

    docker --version

    if systemctl is-active --quiet docker; then

        pass "Docker service is running."

    else

        fail "Docker service is not running."

    fi

    DOCKER_ENABLED=$(systemctl is-enabled docker 2>/dev/null)

    if [ "$DOCKER_ENABLED" = "enabled" ]; then

        pass "Docker is enabled at boot."

    else

        warn "Docker is not enabled at boot."

    fi

else

    fail "Docker is not installed."

fi


# ============================================================================
# 31. DOCKER COMPOSE
# ============================================================================

print_header "33. DOCKER COMPOSE VERIFICATION"

if docker compose version >/dev/null 2>&1; then

    pass "Docker Compose plugin is installed."

    docker compose version

elif command -v docker-compose >/dev/null 2>&1; then

    pass "Standalone docker-compose is installed."

    docker-compose --version

else

    warn "Docker Compose was not found."

fi


# ============================================================================
# 32. DOCKER CONTAINERS
# ============================================================================

print_header "34. DOCKER CONTAINERS"

if command -v docker >/dev/null 2>&1; then

    echo "--- Docker Containers ---"

    sudo docker ps -a

    CONTAINER_COUNT=$(sudo docker ps -aq | wc -l)

    echo
    echo "Container Count: $CONTAINER_COUNT"

    if [ "$CONTAINER_COUNT" -gt 0 ]; then

        pass "Docker container(s) found."

    else

        warn "No Docker containers found."

    fi

fi


# ============================================================================
# 33. DOCKER IMAGES
# ============================================================================

print_header "35. DOCKER IMAGES"

if command -v docker >/dev/null 2>&1; then

    sudo docker images

    IMAGE_COUNT=$(sudo docker images -q | wc -l)

    echo
    echo "Docker Image Count: $IMAGE_COUNT"

    if [ "$IMAGE_COUNT" -gt 0 ]; then

        pass "Docker image(s) found."

    else

        warn "No Docker images found."

    fi

fi


# ============================================================================
# 34. LISTENING PORTS
# ============================================================================

print_header "36. LISTENING PORTS"

if command -v ss >/dev/null 2>&1; then

    sudo ss -tulpn

    pass "Listening ports retrieved."

else

    warn "ss command not available."

fi


# ============================================================================
# 35. GIT
# ============================================================================

print_header "37. GIT VERIFICATION"

if command -v git >/dev/null 2>&1; then

    pass "Git is installed."

    git --version

else

    warn "Git is not installed."

fi


# ============================================================================
# 36. S3 BUCKET COUNT
# ============================================================================

print_header "38. S3 BUCKET VERIFICATION"

S3_BUCKET_LIST=$(aws s3api list-buckets \
    --region "$AWS_REGION" \
    --query "Buckets[*].Name" \
    --output text \
    2>/dev/null)

if [ $? -eq 0 ]; then

    S3_BUCKET_COUNT=$(aws s3api list-buckets \
        --region "$AWS_REGION" \
        --query "length(Buckets)" \
        --output text \
        2>/dev/null)

    echo "S3 Bucket Count: ${S3_BUCKET_COUNT:-0}"

    pass "S3 bucket list retrieved."

    echo
    echo "--- S3 Buckets ---"

    aws s3api list-buckets \
        --region "$AWS_REGION" \
        --query "Buckets[*].[Name,CreationDate]" \
        --output table

else

    fail "Unable to retrieve S3 buckets."

fi


# ============================================================================
# 37. VERIFY EVERY S3 BUCKET
# ============================================================================

print_header "39. VERIFY S3 BUCKETS"

if [ -n "$S3_BUCKET_LIST" ]; then

    for BUCKET in $S3_BUCKET_LIST; do

        echo
        echo "----------------------------------------------------------------------"
        echo "S3 Bucket: $BUCKET"
        echo "----------------------------------------------------------------------"

        echo
        echo "Bucket Region:"

        aws s3api get-bucket-location \
            --bucket "$BUCKET" \
            --output text \
            2>/dev/null || true

        echo
        echo "Versioning:"

        aws s3api get-bucket-versioning \
            --bucket "$BUCKET" \
            --output table \
            2>/dev/null || true

        echo
        echo "Encryption:"

        aws s3api get-bucket-encryption \
            --bucket "$BUCKET" \
            --output table \
            2>/dev/null || true

        echo
        echo "Public Access Block:"

        aws s3api get-public-access-block \
            --bucket "$BUCKET" \
            --output table \
            2>/dev/null || true

        echo
        echo "Object Count:"

        OBJECT_COUNT=$(aws s3api list-objects-v2 \
            --bucket "$BUCKET" \
            --query "KeyCount" \
            --output text \
            2>/dev/null)

        echo "${OBJECT_COUNT:-0}"

        pass "S3 bucket metadata checked: $BUCKET"

    done

else

    warn "No S3 buckets were found."

fi


# ============================================================================
# 38. DISCOVER WEBSITE BUCKET
# ============================================================================

print_header "40. DISCOVER WEBSITE S3 BUCKET"

WEBSITE_BUCKET=$(aws cloudformation describe-stacks \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" \
    --output text \
    2>/dev/null)

if [ -z "$WEBSITE_BUCKET" ] || [ "$WEBSITE_BUCKET" = "None" ]; then

    if [ -n "$EXPECTED_WEBSITE_BUCKET" ]; then

        WEBSITE_BUCKET="$EXPECTED_WEBSITE_BUCKET"

    fi

fi


if [ -n "$WEBSITE_BUCKET" ] && [ "$WEBSITE_BUCKET" != "None" ]; then

    pass "Website S3 bucket identified: $WEBSITE_BUCKET"

else

    warn "Website S3 bucket could not be identified."

fi


# ============================================================================
# 39. WEBSITE BUCKET OBJECTS
# ============================================================================

print_header "41. WEBSITE S3 OBJECTS"

if [ -n "$WEBSITE_BUCKET" ] && [ "$WEBSITE_BUCKET" != "None" ]; then

    echo "Bucket:"
    echo "$WEBSITE_BUCKET"

    echo

    aws s3 ls \
        "s3://$WEBSITE_BUCKET/" \
        --recursive \
        --region "$AWS_REGION"

    OBJECT_COUNT=$(aws s3api list-objects-v2 \
        --bucket "$WEBSITE_BUCKET" \
        --query "KeyCount" \
        --output text \
        2>/dev/null)

    echo
    echo "Website Object Count: ${OBJECT_COUNT:-0}"

    if [ "${OBJECT_COUNT:-0}" -gt 0 ]; then

        pass "Website bucket contains objects."

    else

        warn "Website bucket contains no objects."

    fi

fi


# ============================================================================
# 40. S3 WEBSITE CONFIGURATION
# ============================================================================

print_header "42. S3 WEBSITE CONFIGURATION"

if [ -n "$WEBSITE_BUCKET" ] && [ "$WEBSITE_BUCKET" != "None" ]; then

    echo "--- Website Configuration ---"

    aws s3api get-bucket-website \
        --bucket "$WEBSITE_BUCKET" \
        --output table \
        2>/dev/null

    if [ $? -eq 0 ]; then

        pass "S3 website configuration exists."

    else

        info "S3 static website endpoint is not configured."

        info "This can be normal when CloudFront OAC is used."

    fi

fi


# ============================================================================
# 41. CLOUDFRONT DISTRIBUTIONS
# ============================================================================

print_header "43. CLOUDFRONT DISTRIBUTIONS"

CLOUDFRONT_COUNT=$(aws cloudfront list-distributions \
    --query "length(DistributionList.Items)" \
    --output text \
    2>/dev/null)

echo "CloudFront Distribution Count: ${CLOUDFRONT_COUNT:-0}"

if [ "${CLOUDFRONT_COUNT:-0}" -gt 0 ]; then

    pass "CloudFront distribution(s) found."

    aws cloudfront list-distributions \
        --query "DistributionList.Items[*].[Id,DomainName,Status,Enabled]" \
        --output table

else

    warn "No CloudFront distributions found."

fi


# ============================================================================
# 42. CLOUDFRONT -> S3 ORIGIN
# ============================================================================

print_header "44. CLOUDFRONT -> S3 VERIFICATION"

if [ "${CLOUDFRONT_COUNT:-0}" -gt 0 ]; then

    CLOUDFRONT_IDS=$(aws cloudfront list-distributions \
        --query "DistributionList.Items[*].Id" \
        --output text \
        2>/dev/null)

    for CF_ID in $CLOUDFRONT_IDS; do

        echo
        echo "----------------------------------------------------------------------"
        echo "CloudFront Distribution: $CF_ID"
        echo "----------------------------------------------------------------------"

        CF_DOMAIN=$(aws cloudfront get-distribution \
            --id "$CF_ID" \
            --query "Distribution.DomainName" \
            --output text \
            2>/dev/null)

        CF_STATUS=$(aws cloudfront get-distribution \
            --id "$CF_ID" \
            --query "Distribution.Status" \
            --output text \
            2>/dev/null)

        echo "Domain : $CF_DOMAIN"
        echo "Status : $CF_STATUS"

        echo
        echo "Origins:"

        aws cloudfront get-distribution \
            --id "$CF_ID" \
            --query "Distribution.DistributionConfig.Origins.Items[*].[Id,DomainName,OriginPath]" \
            --output table

        echo
        echo "Default Root Object:"

        aws cloudfront get-distribution \
            --id "$CF_ID" \
            --query "Distribution.DistributionConfig.DefaultRootObject" \
            --output text

        echo
        echo "Origin Access Control:"

        aws cloudfront get-distribution \
            --id "$CF_ID" \
            --query "Distribution.DistributionConfig.Origins.Items[*].OriginAccessControlId" \
            --output text

        if [ "$CF_STATUS" = "Deployed" ]; then

            pass "CloudFront distribution is deployed: $CF_ID"

        else

            warn "CloudFront distribution status is $CF_STATUS: $CF_ID"

        fi

    done

fi


# ============================================================================
# 43. CLOUDFRONT WEBSITE TEST
# ============================================================================

print_header "45. CLOUDFRONT WEBSITE TEST"

CLOUDFRONT_URL=$(aws cloudformation describe-stacks \
    --stack-name "$MAIN_STACK" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CloudFrontWebsiteURL'].OutputValue" \
    --output text \
    2>/dev/null)

if [ -z "$CLOUDFRONT_URL" ] || [ "$CLOUDFRONT_URL" = "None" ]; then

    if [ "${CLOUDFRONT_COUNT:-0}" -gt 0 ]; then

        CF_DOMAIN=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[0].DomainName" \
            --output text \
            2>/dev/null)

        if [ -n "$CF_DOMAIN" ] && [ "$CF_DOMAIN" != "None" ]; then

            CLOUDFRONT_URL="https://$CF_DOMAIN"

        fi

    fi

fi


if [ -n "$CLOUDFRONT_URL" ] && [ "$CLOUDFRONT_URL" != "None" ]; then

    echo "CloudFront URL:"
    echo "$CLOUDFRONT_URL"

    HTTP_STATUS=$(curl -sS \
        -o /dev/null \
        -w "%{http_code}" \
        --connect-timeout 10 \
        --max-time 20 \
        "$CLOUDFRONT_URL/" \
        2>/dev/null)

    echo
    echo "HTTP Status: $HTTP_STATUS"

    if [[ "$HTTP_STATUS" =~ ^2[0-9][0-9]$ ]] || \
       [[ "$HTTP_STATUS" =~ ^3[0-9][0-9]$ ]]; then

        pass "CloudFront website responded successfully."

    else

        fail "CloudFront website did not return a successful response."

    fi

else

    warn "CloudFront website URL could not be identified."

fi


# ============================================================================
# 44. RDS MYSQL
# ============================================================================

print_header "46. RDS MYSQL VERIFICATION"

RDS_IDENTIFIER=$(aws rds describe-db-instances \
    --region "$AWS_REGION" \
    --query "DBInstances[?Engine=='mysql'].DBInstanceIdentifier | [0]" \
    --output text \
    2>/dev/null)

if [ -n "$RDS_IDENTIFIER" ] && [ "$RDS_IDENTIFIER" != "None" ]; then

    pass "RDS MySQL instance found: $RDS_IDENTIFIER"

    aws rds describe-db-instances \
        --db-instance-identifier "$RDS_IDENTIFIER" \
        --region "$AWS_REGION" \
        --query "DBInstances[0].[DBInstanceIdentifier,Engine,EngineVersion,DBInstanceStatus,DBInstanceClass,PubliclyAccessible,Endpoint.Address,Endpoint.Port]" \
        --output table

    RDS_ENDPOINT=$(aws rds describe-db-instances \
        --db-instance-identifier "$RDS_IDENTIFIER" \
        --region "$AWS_REGION" \
        --query "DBInstances[0].Endpoint.Address" \
        --output text)

    RDS_PORT=$(aws rds describe-db-instances \
        --db-instance-identifier "$RDS_IDENTIFIER" \
        --region "$AWS_REGION" \
        --query "DBInstances[0].Endpoint.Port" \
        --output text)

    RDS_STATUS=$(aws rds describe-db-instances \
        --db-instance-identifier "$RDS_IDENTIFIER" \
        --region "$AWS_REGION" \
        --query "DBInstances[0].DBInstanceStatus" \
        --output text)

    RDS_PUBLIC=$(aws rds describe-db-instances \
        --db-instance-identifier "$RDS_IDENTIFIER" \
        --region "$AWS_REGION" \
        --query "DBInstances[0].PubliclyAccessible" \
        --output text)

    if [ "$RDS_STATUS" = "available" ]; then

        pass "RDS status is available."

    else

        warn "RDS status is $RDS_STATUS."

    fi

    if [ "$RDS_PUBLIC" = "False" ]; then

        pass "RDS is not publicly accessible."

    else

        warn "RDS is publicly accessible."

    fi

else

    warn "No MySQL RDS instance found."

fi


# ============================================================================
# 45. RDS NETWORK CONNECTIVITY
# ============================================================================

print_header "47. EC2 -> RDS NETWORK CONNECTIVITY"

if [ -n "$RDS_ENDPOINT" ] && \
   [ "$RDS_ENDPOINT" != "None" ]; then

    echo "RDS Endpoint:"
    echo "$RDS_ENDPOINT"

    echo
    echo "RDS Port:"
    echo "$RDS_PORT"

    if getent hosts "$RDS_ENDPOINT" >/dev/null 2>&1; then

        pass "RDS endpoint resolves from EC2."

    else

        fail "RDS endpoint does not resolve from EC2."

    fi

    if command -v nc >/dev/null 2>&1; then

        if nc -z -w 5 \
            "$RDS_ENDPOINT" \
            "$RDS_PORT" \
            >/dev/null 2>&1; then

            pass "EC2 can reach RDS TCP port $RDS_PORT."

        else

            fail "EC2 cannot reach RDS TCP port $RDS_PORT."

        fi

    else

        warn "nc is not installed; RDS TCP test skipped."

    fi

else

    warn "RDS endpoint unavailable."

fi


# ============================================================================
# 46. SECRETS MANAGER
# ============================================================================

print_header "48. SECRETS MANAGER"

SECRET_COUNT=$(aws secretsmanager list-secrets \
    --region "$AWS_REGION" \
    --query "length(SecretList)" \
    --output text \
    2>/dev/null)

echo "Secret Count: ${SECRET_COUNT:-0}"

if [ "${SECRET_COUNT:-0}" -gt 0 ]; then

    pass "Secrets Manager contains secret(s)."

    echo
    echo "--- Secret Metadata ---"

    # IMPORTANT:
    #
    # Secret VALUE is intentionally never requested.
    #
    aws secretsmanager list-secrets \
        --region "$AWS_REGION" \
        --query "SecretList[*].[Name,ARN,LastChangedDate]" \
        --output table

else

    warn "No Secrets Manager secrets found."

fi


# ============================================================================
# 47. ECR
# ============================================================================

print_header "49. ECR VERIFICATION"

ECR_ERROR_FILE="/tmp/charlie-cafe-ecr-error.txt"

rm -f "$ECR_ERROR_FILE"

echo "Repository:"
echo "$ECR_REPOSITORY"

echo
echo "Region:"
echo "$AWS_REGION"

if aws ecr describe-repositories \
    --repository-names "$ECR_REPOSITORY" \
    --region "$AWS_REGION" \
    >/dev/null \
    2>"$ECR_ERROR_FILE"; then

    pass "ECR repository exists: $ECR_REPOSITORY"

    aws ecr describe-repositories \
        --repository-names "$ECR_REPOSITORY" \
        --region "$AWS_REGION" \
        --query "repositories[0].[repositoryName,repositoryUri,registryId,repositoryArn]" \
        --output table

else

    ECR_ERROR=$(cat "$ECR_ERROR_FILE")

    echo
    echo "--- ECR Error ---"
    echo "$ECR_ERROR"

    if echo "$ECR_ERROR" | grep -qi "RepositoryNotFoundException"; then

        fail "ECR repository does not exist."

    elif echo "$ECR_ERROR" | grep -qi "AccessDenied"; then

        fail "IAM permission denied while accessing ECR."

    else

        fail "ECR verification failed."

    fi

fi

rm -f "$ECR_ERROR_FILE"


# ============================================================================
# 48. ECR IMAGES
# ============================================================================

print_header "50. ECR IMAGES"

if aws ecr describe-repositories \
    --repository-names "$ECR_REPOSITORY" \
    --region "$AWS_REGION" \
    >/dev/null \
    2>&1; then

    ECR_IMAGE_COUNT=$(aws ecr describe-images \
        --repository-name "$ECR_REPOSITORY" \
        --region "$AWS_REGION" \
        --query "length(imageDetails)" \
        --output text \
        2>/dev/null)

    echo "ECR Image Count: ${ECR_IMAGE_COUNT:-0}"

    aws ecr describe-images \
        --repository-name "$ECR_REPOSITORY" \
        --region "$AWS_REGION" \
        --query "imageDetails[*].[imageTags,imageDigest,imagePushedAt,imageSizeInBytes]" \
        --output table \
        2>/dev/null

    if [ "${ECR_IMAGE_COUNT:-0}" -gt 0 ]; then

        pass "ECR contains image(s)."

    else

        warn "ECR repository contains no images."

    fi

else

    warn "ECR image verification skipped because repository is unavailable."

fi


# ============================================================================
# 49. ECS CLOUDFORMATION STACK
# ============================================================================

print_header "51. ECS CLOUDFORMATION STACK"

ECS_STACK_STATUS=$(aws cloudformation describe-stacks \
    --stack-name "$ECS_STACK" \
    --region "$AWS_REGION" \
    --query "Stacks[0].StackStatus" \
    --output text \
    2>/dev/null)

if [ "$ECS_STACK_STATUS" = "CREATE_COMPLETE" ] || \
   [ "$ECS_STACK_STATUS" = "UPDATE_COMPLETE" ]; then

    pass "ECS CloudFormation stack status: $ECS_STACK_STATUS"

else

    warn "ECS CloudFormation stack status: ${ECS_STACK_STATUS:-NOT_FOUND}"

fi


# ============================================================================
# 50. ECS CLUSTER
# ============================================================================

print_header "52. ECS CLUSTER"

ECS_CLUSTER_STATUS=$(aws ecs describe-clusters \
    --clusters "$ECS_CLUSTER" \
    --region "$AWS_REGION" \
    --query "clusters[0].status" \
    --output text \
    2>/dev/null)

if [ "$ECS_CLUSTER_STATUS" = "ACTIVE" ]; then

    pass "ECS cluster is ACTIVE."

    aws ecs describe-clusters \
        --clusters "$ECS_CLUSTER" \
        --region "$AWS_REGION" \
        --query "clusters[0].[clusterName,status,runningTasksCount,pendingTasksCount,activeServicesCount]" \
        --output table

else

    fail "ECS cluster status: ${ECS_CLUSTER_STATUS:-NOT_FOUND}"

fi


# ============================================================================
# 51. ECS SERVICE
# ============================================================================

print_header "53. ECS SERVICE"

ECS_SERVICE_STATUS=$(aws ecs describe-services \
    --cluster "$ECS_CLUSTER" \
    --services "$ECS_SERVICE" \
    --region "$AWS_REGION" \
    --query "services[0].status" \
    --output text \
    2>/dev/null)

if [ "$ECS_SERVICE_STATUS" = "ACTIVE" ]; then

    pass "ECS service is ACTIVE."

    aws ecs describe-services \
        --cluster "$ECS_CLUSTER" \
        --services "$ECS_SERVICE" \
        --region "$AWS_REGION" \
        --query "services[0].[serviceName,status,desiredCount,runningCount,pendingCount,launchType]" \
        --output table

    ECS_DESIRED_COUNT=$(aws ecs describe-services \
        --cluster "$ECS_CLUSTER" \
        --services "$ECS_SERVICE" \
        --region "$AWS_REGION" \
        --query "services[0].desiredCount" \
        --output text)

    ECS_RUNNING_COUNT=$(aws ecs describe-services \
        --cluster "$ECS_CLUSTER" \
        --services "$ECS_SERVICE" \
        --region "$AWS_REGION" \
        --query "services[0].runningCount" \
        --output text)

    echo
    echo "Desired Tasks : $ECS_DESIRED_COUNT"
    echo "Running Tasks : $ECS_RUNNING_COUNT"

    if [ "$ECS_RUNNING_COUNT" -eq "$ECS_DESIRED_COUNT" ]; then

        pass "ECS running task count matches desired count."

    else

        warn "ECS running count does not match desired count."

    fi

else

    fail "ECS service status: ${ECS_SERVICE_STATUS:-NOT_FOUND}"

fi


# ============================================================================
# 52. ECS TASKS
# ============================================================================

print_header "54. ECS RUNNING TASKS"

TASK_ARNS=$(aws ecs list-tasks \
    --cluster "$ECS_CLUSTER" \
    --service-name "$ECS_SERVICE" \
    --desired-status RUNNING \
    --region "$AWS_REGION" \
    --query "taskArns[]" \
    --output text \
    2>/dev/null)

if [ -n "$TASK_ARNS" ] && \
   [ "$TASK_ARNS" != "None" ]; then

    pass "Running ECS task(s) found."

    aws ecs describe-tasks \
        --cluster "$ECS_CLUSTER" \
        --tasks $TASK_ARNS \
        --region "$AWS_REGION" \
        --query "tasks[*].[taskArn,lastStatus,healthStatus,launchType,taskDefinitionArn]" \
        --output table

else

    warn "No running ECS tasks found."

fi


# ============================================================================
# 53. ECS TASK HEALTH
# ============================================================================

print_header "55. ECS TASK HEALTH"

if [ -n "$TASK_ARNS" ] && \
   [ "$TASK_ARNS" != "None" ]; then

    TASK_HEALTH=$(aws ecs describe-tasks \
        --cluster "$ECS_CLUSTER" \
        --tasks $TASK_ARNS \
        --region "$AWS_REGION" \
        --query "tasks[*].[lastStatus,healthStatus]" \
        --output text \
        2>/dev/null)

    echo "$TASK_HEALTH"

    if echo "$TASK_HEALTH" | grep -q "RUNNING"; then

        pass "At least one ECS task is RUNNING."

    else

        warn "No RUNNING ECS task detected."

    fi

fi


# ============================================================================
# 54. APPLICATION LOAD BALANCER
# ============================================================================

print_header "56. APPLICATION LOAD BALANCER"

ALB_ARN=$(aws elbv2 describe-load-balancers \
    --region "$AWS_REGION" \
    --query "LoadBalancers[?Type=='application'].LoadBalancerArn | [0]" \
    --output text \
    2>/dev/null)

if [ -n "$ALB_ARN" ] && \
   [ "$ALB_ARN" != "None" ]; then

    pass "Application Load Balancer found."

    aws elbv2 describe-load-balancers \
        --load-balancer-arns "$ALB_ARN" \
        --region "$AWS_REGION" \
        --query "LoadBalancers[0].[LoadBalancerName,DNSName,Scheme,Type,State.Code,VpcId]" \
        --output table

    ALB_DNS=$(aws elbv2 describe-load-balancers \
        --load-balancer-arns "$ALB_ARN" \
        --region "$AWS_REGION" \
        --query "LoadBalancers[0].DNSName" \
        --output text)

    ALB_STATE=$(aws elbv2 describe-load-balancers \
        --load-balancer-arns "$ALB_ARN" \
        --region "$AWS_REGION" \
        --query "LoadBalancers[0].State.Code" \
        --output text)

    if [ "$ALB_STATE" = "active" ]; then

        pass "Application Load Balancer is active."

    else

        warn "ALB state is $ALB_STATE."

    fi

else

    warn "No Application Load Balancer found."

fi


# ============================================================================
# 55. ALB LISTENERS
# ============================================================================

print_header "57. ALB LISTENERS"

if [ -n "$ALB_ARN" ] && [ "$ALB_ARN" != "None" ]; then

    LISTENER_COUNT=$(aws elbv2 describe-listeners \
        --load-balancer-arn "$ALB_ARN" \
        --region "$AWS_REGION" \
        --query "length(Listeners)" \
        --output text \
        2>/dev/null)

    echo "Listener Count: ${LISTENER_COUNT:-0}"

    aws elbv2 describe-listeners \
        --load-balancer-arn "$ALB_ARN" \
        --region "$AWS_REGION" \
        --query "Listeners[*].[ListenerArn,Protocol,Port,DefaultActions[0].Type]" \
        --output table

    if [ "${LISTENER_COUNT:-0}" -gt 0 ]; then

        pass "ALB listener(s) found."

    else

        fail "No ALB listeners found."

    fi

fi


# ============================================================================
# 56. TARGET GROUPS
# ============================================================================

print_header "58. ALB TARGET GROUPS"

TARGET_GROUPS=""

if [ -n "$ALB_ARN" ] && [ "$ALB_ARN" != "None" ]; then

    TARGET_GROUPS=$(aws elbv2 describe-target-groups \
        --load-balancer-arn "$ALB_ARN" \
        --region "$AWS_REGION" \
        --query "TargetGroups[*].TargetGroupArn" \
        --output text \
        2>/dev/null)

    if [ -n "$TARGET_GROUPS" ] && \
       [ "$TARGET_GROUPS" != "None" ]; then

        pass "ALB target group(s) found."

        aws elbv2 describe-target-groups \
            --load-balancer-arn "$ALB_ARN" \
            --region "$AWS_REGION" \
            --query "TargetGroups[*].[TargetGroupName,Protocol,Port,TargetType,HealthCheckProtocol,HealthCheckPort,HealthCheckPath]" \
            --output table

    else

        warn "No target groups found."

    fi

fi


# ============================================================================
# 57. TARGET HEALTH
# ============================================================================

print_header "59. ALB TARGET HEALTH"

if [ -n "$TARGET_GROUPS" ] && \
   [ "$TARGET_GROUPS" != "None" ]; then

    for TG in $TARGET_GROUPS; do

        echo
        echo "----------------------------------------------------------------------"
        echo "Target Group"
        echo "$TG"
        echo "----------------------------------------------------------------------"

        aws elbv2 describe-target-health \
            --target-group-arn "$TG" \
            --region "$AWS_REGION" \
            --query "TargetHealthDescriptions[*].[Target.Id,Target.Port,TargetHealth.State,TargetHealth.Reason,TargetHealth.Description]" \
            --output table

        HEALTHY_COUNT=$(aws elbv2 describe-target-health \
            --target-group-arn "$TG" \
            --region "$AWS_REGION" \
            --query "length(TargetHealthDescriptions[?TargetHealth.State=='healthy'])" \
            --output text \
            2>/dev/null)

        echo
        echo "Healthy Targets: ${HEALTHY_COUNT:-0}"

        if [ "${HEALTHY_COUNT:-0}" -gt 0 ]; then

            pass "Healthy ALB target(s) found."

        else

            fail "No healthy ALB targets found."

        fi

    done

fi


# ============================================================================
# 58. ALB HTTP TEST
# ============================================================================

print_header "60. APPLICATION HTTP TEST THROUGH ALB"

if [ -n "$ALB_DNS" ] && \
   [ "$ALB_DNS" != "None" ]; then

    echo "ALB DNS:"
    echo "$ALB_DNS"

    HTTP_STATUS=$(curl -sS \
        -o /dev/null \
        -w "%{http_code}" \
        --connect-timeout 10 \
        --max-time 20 \
        "http://$ALB_DNS/" \
        2>/dev/null)

    echo
    echo "HTTP Status: $HTTP_STATUS"

    if [[ "$HTTP_STATUS" =~ ^2[0-9][0-9]$ ]] || \
       [[ "$HTTP_STATUS" =~ ^3[0-9][0-9]$ ]]; then

        pass "Application responded successfully through ALB."

    else

        fail "Application did not return a successful response through ALB."

    fi

else

    warn "ALB DNS unavailable; HTTP test skipped."

fi


# ============================================================================
# 59. CLOUDWATCH LOGS
# ============================================================================

print_header "61. CLOUDWATCH LOGS"

LOG_GROUP_EXISTS=$(aws logs describe-log-groups \
    --log-group-name-prefix "$LOG_GROUP" \
    --region "$AWS_REGION" \
    --query "logGroups[?logGroupName=='$LOG_GROUP'].logGroupName" \
    --output text \
    2>/dev/null)

if [ "$LOG_GROUP_EXISTS" = "$LOG_GROUP" ]; then

    pass "CloudWatch log group exists: $LOG_GROUP"

    echo
    echo "--- Recent CloudWatch Logs ---"

    aws logs tail "$LOG_GROUP" \
        --since 10m \
        --format short \
        --region "$AWS_REGION" \
        2>/dev/null || true

else

    warn "CloudWatch log group not found: $LOG_GROUP"

fi


# ============================================================================
# 60. FINAL EC2 -> RDS TEST
# ============================================================================

print_header "62. FINAL EC2 -> RDS CONNECTIVITY"

if [ -n "$RDS_ENDPOINT" ] && \
   [ "$RDS_ENDPOINT" != "None" ]; then

    if command -v nc >/dev/null 2>&1; then

        if nc -z -w 5 \
            "$RDS_ENDPOINT" \
            "$RDS_PORT" \
            >/dev/null 2>&1; then

            pass "Final EC2 -> RDS connectivity verified."

        else

            fail "Final EC2 -> RDS connectivity failed."

        fi

    else

        warn "nc is not installed. Final RDS connectivity test skipped."

    fi

else

    warn "RDS endpoint unavailable."

fi


# ============================================================================
# 61. FINAL SUMMARY
# ============================================================================

print_header "FINAL CLOUDFORMATION DEVOPS LAB VERIFICATION SUMMARY"

echo
echo "AWS Region      : $AWS_REGION"
echo "AWS Account     : ${AWS_ACCOUNT_ID:-Unknown}"
echo "AWS Identity    : ${AWS_CALLER_ARN:-Unknown}"
echo "EC2 Instance    : ${INSTANCE_ID:-Unknown}"
echo "VPC             : ${VPC_ID:-Unknown}"
echo "RDS Instance    : ${RDS_IDENTIFIER:-Unknown}"
echo "RDS Endpoint    : ${RDS_ENDPOINT:-Unknown}"
echo "Website Bucket  : ${WEBSITE_BUCKET:-Unknown}"
echo "CloudFront URL  : ${CLOUDFRONT_URL:-Unknown}"
echo "ALB DNS         : ${ALB_DNS:-Unknown}"
echo "ECS Cluster     : $ECS_CLUSTER"
echo "ECS Service     : $ECS_SERVICE"
echo

echo "----------------------------------------------------------------------"

echo "PASSED TESTS : $PASS_COUNT"

echo "FAILED TESTS : $FAIL_COUNT"

echo "WARNINGS     : $WARN_COUNT"

echo "----------------------------------------------------------------------"

echo


if [ "$FAIL_COUNT" -eq 0 ]; then

    echo "======================================================================"
    echo "RESULT: AWS CLOUDFORMATION DEVOPS LAB VERIFICATION PASSED"
    echo "======================================================================"

    echo
    echo "All critical verification checks completed without failures."

else

    echo "======================================================================"
    echo "RESULT: AWS CLOUDFORMATION DEVOPS LAB HAS FAILURES"
    echo "======================================================================"

    echo
    echo "Review all [FAIL] messages above."

fi


echo
echo "======================================================================"
echo "VERIFICATION COMPLETED"
echo "======================================================================"

echo
echo "This script performs read-only verification."
echo
echo "It does not intentionally modify AWS resources."
echo
echo "Configured AWS Region: $AWS_REGION"
echo